apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apicurio-registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm-charts.touk.pl/public/
    chart: apicurio-registry
    targetRevision: 0.1.5
    helm:
      releaseName: apicurio-registry
      values: |
        replicaCount: 1

        kafka:
          enabled: false  # Disable bundled Kafka since you already have Strimzi

        global:
          kafka:
            bootstrapServers: "my-cluster-kafka-bootstrap.platform.svc:9092"  # ✅ Use your existing Kafka

        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 1Gi

        service:
          type: ClusterIP

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
