
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-semantics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/Daniel-Makhoba-Emmanuel/kafka-k8s-lab.git   
    targetRevision: 'main'
    path: manifests/kafka-semantics
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true