apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-eos
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-eos
  template:
    metadata:
      labels:
        app: consumer-eos
    spec:
      containers:
        - name: consumer
          image: confluentinc/cp-kafka:7.6.1
          command: ["/bin/sh", "-c"]
          args:
            - >
              echo "Exactly-once semantics (EOS) require a producer configured with
              'enable.idempotence=true' and 'transactional.id'. This cannot be
              simulated with kafka-console-consumer. Replace this placeholder with
              a custom app if you want to demo EOS in practice.";
              sleep 3600
